import { ColumnDef, FieldDef } from "./types";

export interface ModuleConfig {
  table: string;
  singular: string;
  plural: string;
  icon: string;
  columns: ColumnDef[];
  formFields: FieldDef[];
  searchField?: string;
  defaultSort?: { column: string; ascending: boolean };
  projectScoped?: boolean;
}

// Status options reused across modules
const STATUS_OPTS = (values: string[]) =>
  values.map((v) => ({ value: v, label: v.charAt(0).toUpperCase() + v.slice(1).replace(/_/g, " ") }));

const PRIORITY_OPTS = STATUS_OPTS(["low", "medium", "high", "critical"]);

// ============================================================
// COMPANY-LEVEL MODULES
// ============================================================

export const directoryModule: ModuleConfig = {
  table: "directory_contacts",
  singular: "Contact",
  plural: "Directory",
  icon: "users",
  searchField: "company_name",
  columns: [
    { key: "company_name", header: "Company" },
    { key: "first_name", header: "First Name" },
    { key: "last_name", header: "Last Name" },
    { key: "contact_type", header: "Type", type: "badge" },
    { key: "email", header: "Email" },
    { key: "phone", header: "Phone" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "company_name", label: "Company Name", type: "text", span: 2 },
    { key: "contact_type", label: "Type", type: "select", required: true, options: STATUS_OPTS(["employee", "subcontractor", "vendor", "architect", "engineer", "owner"]) },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "inactive", "pending"]), defaultValue: "active" },
    { key: "first_name", label: "First Name", type: "text" },
    { key: "last_name", label: "Last Name", type: "text" },
    { key: "title", label: "Title", type: "text" },
    { key: "email", label: "Email", type: "email" },
    { key: "phone", label: "Phone", type: "text" },
    { key: "mobile", label: "Mobile", type: "text" },
    { key: "address", label: "Address", type: "text", span: 2 },
    { key: "city", label: "City", type: "text" },
    { key: "state", label: "State", type: "text" },
    { key: "zip", label: "ZIP", type: "text" },
    { key: "license_number", label: "License #", type: "text" },
    { key: "insurance_provider", label: "Insurance Provider", type: "text" },
    { key: "insurance_policy_number", label: "Policy #", type: "text" },
    { key: "insurance_expiry", label: "Insurance Expiry", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const bidsModule: ModuleConfig = {
  table: "bids",
  singular: "Bid",
  plural: "Bids",
  icon: "gavel",
  searchField: "title",
  columns: [
    { key: "bid_package", header: "Package" },
    { key: "title", header: "Title" },
    { key: "bidder_name", header: "Bidder" },
    { key: "bid_amount", header: "Amount", type: "currency" },
    { key: "due_date", header: "Due Date", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "bid_package", label: "Bid Package", type: "text" },
    { key: "title", label: "Title", type: "text", required: true },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "invited", "submitted", "awarded", "rejected", "withdrawn"]), defaultValue: "draft" },
    { key: "bidder_name", label: "Bidder", type: "text" },
    { key: "bid_amount", label: "Bid Amount", type: "currency" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "submitted_date", label: "Submitted Date", type: "date" },
    { key: "awarded_date", label: "Awarded Date", type: "date" },
    { key: "scope_of_work", label: "Scope of Work", type: "textarea", span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
  projectScoped: true,
};

export const prequalModule: ModuleConfig = {
  table: "prequalifications",
  singular: "Prequalification",
  plural: "Prequalifications",
  icon: "shield-check",
  searchField: "company_name",
  columns: [
    { key: "company_name", header: "Company" },
    { key: "status", header: "Status", type: "status" },
    { key: "score", header: "Score" },
    { key: "financial_rating", header: "Financial" },
    { key: "safety_rating", header: "Safety" },
    { key: "bonding_capacity", header: "Bonding Capacity", type: "currency" },
    { key: "expiry_date", header: "Expiry", type: "date" },
  ],
  formFields: [
    { key: "company_name", label: "Company Name", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["pending", "approved", "rejected", "expired"]), defaultValue: "pending" },
    { key: "score", label: "Score", type: "number" },
    { key: "financial_rating", label: "Financial Rating", type: "select", options: STATUS_OPTS(["excellent", "good", "fair", "poor"]) },
    { key: "safety_rating", label: "Safety Rating", type: "select", options: STATUS_OPTS(["excellent", "good", "fair", "poor"]) },
    { key: "experience_rating", label: "Experience Rating", type: "select", options: STATUS_OPTS(["excellent", "good", "fair", "poor"]) },
    { key: "bonding_capacity", label: "Bonding Capacity", type: "currency" },
    { key: "emr", label: "EMR", type: "number" },
    { key: "osha_recordable_rate", label: "OSHA Recordable Rate", type: "number" },
    { key: "submitted_date", label: "Submitted", type: "date" },
    { key: "reviewed_date", label: "Reviewed", type: "date" },
    { key: "expiry_date", label: "Expiry Date", type: "date" },
    { key: "reviewer", label: "Reviewer", type: "text" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const trainingModule: ModuleConfig = {
  table: "training",
  singular: "Training",
  plural: "Training",
  icon: "graduation-cap",
  searchField: "title",
  columns: [
    { key: "title", header: "Title" },
    { key: "training_type", header: "Type", type: "badge" },
    { key: "instructor", header: "Instructor" },
    { key: "location", header: "Location" },
    { key: "training_date", header: "Date", type: "date" },
    { key: "duration_hours", header: "Hours" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "training_type", label: "Type", type: "select", options: STATUS_OPTS(["safety", "osha", "equipment", "orientation", "other"]), defaultValue: "safety" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["scheduled", "completed", "cancelled"]), defaultValue: "scheduled" },
    { key: "instructor", label: "Instructor", type: "text" },
    { key: "location", label: "Location", type: "text" },
    { key: "training_date", label: "Date", type: "date" },
    { key: "duration_hours", label: "Duration (hours)", type: "number" },
    { key: "certification_required", label: "Certification Required", type: "checkbox" },
    { key: "expiry_period_days", label: "Cert Expiry (days)", type: "number" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

// ============================================================
// PROJECT-LEVEL MODULES
// ============================================================

export const rfisModule: ModuleConfig = {
  table: "rfis",
  singular: "RFI",
  plural: "RFIs",
  icon: "help-circle",
  searchField: "subject",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "subject", header: "Subject" },
    { key: "status", header: "Status", type: "status" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "due_date", header: "Due Date", type: "date" },
  ],
  formFields: [
    { key: "number", label: "RFI #", type: "text" },
    { key: "subject", label: "Subject", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "open", "closed"]), defaultValue: "open" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "responded_date", label: "Responded Date", type: "date" },
    { key: "question", label: "Question", type: "textarea", required: true, span: 2 },
    { key: "answer", label: "Answer", type: "textarea", span: 2 },
  ],
};

export const submittalsModule: ModuleConfig = {
  table: "submittals",
  singular: "Submittal",
  plural: "Submittals",
  icon: "file-check",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "spec_section", header: "Spec Section" },
    { key: "status", header: "Status", type: "status" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "due_date", header: "Due Date", type: "date" },
  ],
  formFields: [
    { key: "number", label: "Submittal #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "spec_section", label: "Spec Section", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "open", "approved", "rejected", "revise_and_resubmit"]), defaultValue: "open" },
    { key: "submitted_by", label: "Submitted By", type: "text" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "approved_date", label: "Approved Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const drawingsModule: ModuleConfig = {
  table: "drawings",
  singular: "Drawing",
  plural: "Drawings",
  icon: "blueprint",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "drawing_number", header: "Number" },
    { key: "title", header: "Title" },
    { key: "discipline", header: "Discipline", type: "badge" },
    { key: "set_name", header: "Set" },
    { key: "revision", header: "Rev" },
    { key: "revision_date", header: "Rev Date", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "drawing_number", label: "Drawing #", type: "text", required: true },
    { key: "title", label: "Title", type: "text", required: true },
    { key: "set_name", label: "Set Name", type: "text" },
    { key: "discipline", label: "Discipline", type: "select", options: STATUS_OPTS(["architectural", "structural", "mechanical", "electrical", "plumbing", "civil"]) },
    { key: "revision", label: "Revision", type: "text" },
    { key: "revision_date", label: "Rev Date", type: "date" },
    { key: "received_date", label: "Received Date", type: "date" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["current", "superseded", "void"]), defaultValue: "current" },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const specificationsModule: ModuleConfig = {
  table: "specifications",
  singular: "Specification",
  plural: "Specifications",
  icon: "book-open",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "section_number", header: "Section" },
    { key: "title", header: "Title" },
    { key: "division", header: "Division" },
    { key: "revision", header: "Revision" },
    { key: "revision_date", header: "Rev Date", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "section_number", label: "Section Number", type: "text", required: true },
    { key: "title", label: "Title", type: "text", required: true },
    { key: "division", label: "Division", type: "text" },
    { key: "revision", label: "Revision", type: "text" },
    { key: "revision_date", label: "Rev Date", type: "date" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["current", "superseded", "void"]), defaultValue: "current" },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const scheduleModule: ModuleConfig = {
  table: "schedule_tasks",
  singular: "Task",
  plural: "Schedule",
  icon: "gantt-chart",
  searchField: "task_name",
  projectScoped: true,
  columns: [
    { key: "wbs", header: "WBS" },
    { key: "task_name", header: "Task" },
    { key: "start_date", header: "Start", type: "date" },
    { key: "end_date", header: "End", type: "date" },
    { key: "duration_days", header: "Days" },
    { key: "percent_complete", header: "% Complete" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "task_name", label: "Task Name", type: "text", required: true, span: 2 },
    { key: "wbs", label: "WBS Code", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["not_started", "in_progress", "completed", "delayed"]), defaultValue: "not_started" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "duration_days", label: "Duration (days)", type: "number" },
    { key: "percent_complete", label: "% Complete", type: "number" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "milestone", label: "Milestone", type: "checkbox" },
    { key: "critical_path", label: "Critical Path", type: "checkbox" },
    { key: "sort_order", label: "Sort Order", type: "number" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const budgetModule: ModuleConfig = {
  table: "budgets",
  singular: "Budget Line",
  plural: "Budget",
  icon: "dollar-sign",
  searchField: "description",
  projectScoped: true,
  columns: [
    { key: "code", header: "Cost Code" },
    { key: "description", header: "Description" },
    { key: "category", header: "Category" },
    { key: "original_amount", header: "Original", type: "currency" },
    { key: "revised_amount", header: "Revised", type: "currency" },
    { key: "committed_amount", header: "Committed", type: "currency" },
    { key: "actual_amount", header: "Actual", type: "currency" },
    { key: "variance", header: "Variance", type: "currency" },
  ],
  formFields: [
    { key: "code", label: "Cost Code", type: "text", required: true },
    { key: "description", label: "Description", type: "text", required: true, span: 2 },
    { key: "category", label: "Category", type: "text" },
    { key: "original_amount", label: "Original Amount", type: "currency" },
    { key: "revised_amount", label: "Revised Amount", type: "currency" },
    { key: "committed_amount", label: "Committed Amount", type: "currency" },
    { key: "actual_amount", label: "Actual Amount", type: "currency" },
    { key: "variance", label: "Variance", type: "currency" },
  ],
};

export const primeContractsModule: ModuleConfig = {
  table: "prime_contracts",
  singular: "Prime Contract",
  plural: "Prime Contracts",
  icon: "file-text",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "owner_company", header: "Owner" },
    { key: "contract_amount", header: "Amount", type: "currency" },
    { key: "status", header: "Status", type: "status" },
    { key: "executed_date", header: "Executed", type: "date" },
  ],
  formFields: [
    { key: "number", label: "Contract #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "owner_company", label: "Owner Company", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "pending", "approved", "executed", "closed"]), defaultValue: "draft" },
    { key: "contract_amount", label: "Contract Amount", type: "currency" },
    { key: "retainage_percent", label: "Retainage %", type: "number" },
    { key: "executed_date", label: "Executed Date", type: "date" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "completion_date", label: "Completion Date", type: "date" },
    { key: "billing_schedule", label: "Billing Schedule", type: "select", options: STATUS_OPTS(["monthly", "biweekly", "milestone"]) },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "terms", label: "Terms", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const commitmentsModule: ModuleConfig = {
  table: "commitments",
  singular: "Commitment",
  plural: "Commitments",
  icon: "handshake",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "commitment_type", header: "Type", type: "badge" },
    { key: "vendor_name", header: "Vendor" },
    { key: "contract_amount", header: "Amount", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Commitment #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "commitment_type", label: "Type", type: "select", options: STATUS_OPTS(["subcontract", "purchase_order"]), defaultValue: "subcontract" },
    { key: "vendor_name", label: "Vendor", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "pending", "approved", "executed", "closed", "void"]), defaultValue: "draft" },
    { key: "contract_amount", label: "Amount", type: "currency" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "retainage_percent", label: "Retainage %", type: "number" },
    { key: "executed_date", label: "Executed Date", type: "date" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "completion_date", label: "Completion Date", type: "date" },
    { key: "scope_of_work", label: "Scope of Work", type: "textarea", span: 2 },
    { key: "terms", label: "Terms", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const changeEventsModule: ModuleConfig = {
  table: "change_events",
  singular: "Change Event",
  plural: "Change Events",
  icon: "alert-triangle",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "event_type", header: "Type", type: "badge" },
    { key: "origin", header: "Origin" },
    { key: "estimated_amount", header: "Est Amount", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "CE #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "event_type", label: "Event Type", type: "select", options: STATUS_OPTS(["owner", "design", "field", "unforeseen"]) },
    { key: "origin", label: "Origin", type: "select", options: STATUS_OPTS(["rfi", "field_directive", "design_change", "owner_request"]) },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["open", "pending", "approved", "rejected", "void"]), defaultValue: "open" },
    { key: "estimated_amount", label: "Estimated Amount", type: "currency" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const commitmentCOsModule: ModuleConfig = {
  table: "commitment_change_orders",
  singular: "Commitment CO",
  plural: "Commitment COs",
  icon: "refresh-cw",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "vendor", header: "Vendor" },
    { key: "amount", header: "Amount", type: "currency" },
    { key: "status", header: "Status", type: "status" },
    { key: "approved_date", header: "Approved", type: "date" },
  ],
  formFields: [
    { key: "number", label: "CO #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "pending", "approved", "rejected"]), defaultValue: "draft" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "reason", label: "Reason", type: "text" },
    { key: "approved_date", label: "Approved Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const contractCOsModule: ModuleConfig = {
  table: "contract_change_orders",
  singular: "Prime Contract CO",
  plural: "Prime Contract COs",
  icon: "refresh-cw",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "amount", header: "Amount", type: "currency" },
    { key: "status", header: "Status", type: "status" },
    { key: "approved_date", header: "Approved", type: "date" },
  ],
  formFields: [
    { key: "number", label: "CO #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "pending", "approved", "rejected"]), defaultValue: "draft" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "reason", label: "Reason", type: "text" },
    { key: "approved_date", label: "Approved Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const ownerInvoicesModule: ModuleConfig = {
  table: "owner_invoices",
  singular: "Owner Invoice",
  plural: "Owner Invoices",
  icon: "receipt",
  searchField: "number",
  projectScoped: true,
  columns: [
    { key: "number", header: "Invoice #" },
    { key: "billing_period_start", header: "Period Start", type: "date" },
    { key: "billing_period_end", header: "Period End", type: "date" },
    { key: "total_completed", header: "Total Completed", type: "currency" },
    { key: "retainage", header: "Retainage", type: "currency" },
    { key: "amount_due", header: "Amount Due", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Invoice #", type: "text", required: true },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved", "paid", "rejected"]), defaultValue: "draft" },
    { key: "billing_period_start", label: "Period Start", type: "date" },
    { key: "billing_period_end", label: "Period End", type: "date" },
    { key: "scheduled_value", label: "Scheduled Value", type: "currency" },
    { key: "work_completed_previous", label: "Previous Work", type: "currency" },
    { key: "work_completed_current", label: "Current Work", type: "currency" },
    { key: "materials_stored", label: "Materials Stored", type: "currency" },
    { key: "total_completed", label: "Total Completed", type: "currency" },
    { key: "retainage", label: "Retainage", type: "currency" },
    { key: "amount_due", label: "Amount Due", type: "currency" },
    { key: "submitted_date", label: "Submitted Date", type: "date" },
    { key: "approved_date", label: "Approved Date", type: "date" },
    { key: "paid_date", label: "Paid Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const subInvoicesModule: ModuleConfig = {
  table: "subcontractor_invoices",
  singular: "Sub Invoice",
  plural: "Sub Invoices",
  icon: "receipt",
  searchField: "vendor_name",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "vendor_name", header: "Vendor" },
    { key: "billing_period_end", header: "Period End", type: "date" },
    { key: "total_completed", header: "Completed", type: "currency" },
    { key: "amount_due", header: "Amount Due", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Invoice #", type: "text" },
    { key: "vendor_name", label: "Vendor", type: "text", required: true },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved", "paid", "rejected"]), defaultValue: "draft" },
    { key: "billing_period_start", label: "Period Start", type: "date" },
    { key: "billing_period_end", label: "Period End", type: "date" },
    { key: "scheduled_value", label: "Scheduled Value", type: "currency" },
    { key: "work_completed_previous", label: "Previous Work", type: "currency" },
    { key: "work_completed_current", label: "Current Work", type: "currency" },
    { key: "materials_stored", label: "Materials Stored", type: "currency" },
    { key: "total_completed", label: "Total Completed", type: "currency" },
    { key: "retainage", label: "Retainage", type: "currency" },
    { key: "amount_due", label: "Amount Due", type: "currency" },
    { key: "submitted_date", label: "Submitted", type: "date" },
    { key: "approved_date", label: "Approved", type: "date" },
    { key: "paid_date", label: "Paid", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const directCostsModule: ModuleConfig = {
  table: "direct_costs",
  singular: "Direct Cost",
  plural: "Direct Costs",
  icon: "credit-card",
  searchField: "description",
  projectScoped: true,
  columns: [
    { key: "cost_type", header: "Type", type: "badge" },
    { key: "description", header: "Description" },
    { key: "vendor", header: "Vendor" },
    { key: "cost_code", header: "Cost Code" },
    { key: "amount", header: "Amount", type: "currency" },
    { key: "cost_date", header: "Date", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "cost_type", label: "Cost Type", type: "select", options: STATUS_OPTS(["labor", "expense", "equipment", "other"]), defaultValue: "expense" },
    { key: "description", label: "Description", type: "text", required: true, span: 2 },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["pending", "approved", "paid"]), defaultValue: "pending" },
    { key: "amount", label: "Amount", type: "currency" },
    { key: "quantity", label: "Quantity", type: "number" },
    { key: "unit", label: "Unit", type: "text" },
    { key: "unit_cost", label: "Unit Cost", type: "currency" },
    { key: "invoice_number", label: "Invoice #", type: "text" },
    { key: "cost_date", label: "Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const dailyLogsModule: ModuleConfig = {
  table: "daily_logs",
  singular: "Daily Log",
  plural: "Daily Logs",
  icon: "sun",
  searchField: "work_performed",
  projectScoped: true,
  columns: [
    { key: "log_date", header: "Date", type: "date" },
    { key: "weather_condition", header: "Weather", type: "badge" },
    { key: "temperature_high", header: "High" },
    { key: "temperature_low", header: "Low" },
    { key: "status", header: "Status", type: "status" },
    { key: "created_by", header: "Created By" },
  ],
  formFields: [
    { key: "log_date", label: "Date", type: "date", required: true },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved"]), defaultValue: "draft" },
    { key: "weather_condition", label: "Weather", type: "select", options: STATUS_OPTS(["sunny", "cloudy", "rain", "snow", "fog", "wind"]) },
    { key: "temperature_high", label: "High Temp (F)", type: "number" },
    { key: "temperature_low", label: "Low Temp (F)", type: "number" },
    { key: "wind_speed", label: "Wind Speed", type: "text" },
    { key: "precipitation", label: "Precipitation", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "approved_by", label: "Approved By", type: "text" },
    { key: "work_performed", label: "Work Performed", type: "textarea", span: 2 },
    { key: "delays", label: "Delays", type: "textarea", span: 2 },
    { key: "safety_notes", label: "Safety Notes", type: "textarea", span: 2 },
    { key: "materials_received", label: "Materials Received", type: "textarea", span: 2 },
  ],
};

export const punchListModule: ModuleConfig = {
  table: "punch_list_items",
  singular: "Punch Item",
  plural: "Punch List",
  icon: "check-square",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "location", header: "Location" },
    { key: "trade", header: "Trade" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "ball_in_court", header: "Ball In Court" },
    { key: "status", header: "Status", type: "status" },
    { key: "due_date", header: "Due", type: "date" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["open", "in_progress", "ready_for_review", "closed", "void"]), defaultValue: "open" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "location", label: "Location", type: "text" },
    { key: "trade", label: "Trade", type: "text" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "ball_in_court", label: "Ball In Court", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "completed_date", label: "Completed Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const meetingsModule: ModuleConfig = {
  table: "meeting_minutes",
  singular: "Meeting",
  plural: "Meetings",
  icon: "calendar",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "meeting_date", header: "Date", type: "date" },
    { key: "location", header: "Location" },
    { key: "status", header: "Status", type: "status" },
    { key: "created_by", header: "Created By" },
  ],
  formFields: [
    { key: "number", label: "Meeting #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "in_progress", "closed"]), defaultValue: "draft" },
    { key: "meeting_date", label: "Date", type: "date" },
    { key: "location", label: "Location", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "agenda", label: "Agenda", type: "textarea", span: 2 },
    { key: "notes", label: "Minutes / Notes", type: "textarea", span: 2 },
  ],
};

export const documentsModule: ModuleConfig = {
  table: "documents",
  singular: "Document",
  plural: "Documents",
  icon: "folder",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Name" },
    { key: "folder", header: "Folder" },
    { key: "version", header: "Version" },
    { key: "uploaded_by", header: "Uploaded By" },
    { key: "created_at", header: "Uploaded", type: "date" },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true, span: 2 },
    { key: "folder", label: "Folder", type: "text", defaultValue: "/" },
    { key: "version", label: "Version", type: "number", defaultValue: 1 },
    { key: "uploaded_by", label: "Uploaded By", type: "text" },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const photosModule: ModuleConfig = {
  table: "photos",
  singular: "Photo",
  plural: "Photos",
  icon: "camera",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "title", header: "Title" },
    { key: "album", header: "Album" },
    { key: "location", header: "Location" },
    { key: "trade", header: "Trade" },
    { key: "taken_date", header: "Taken", type: "date" },
    { key: "uploaded_by", header: "Uploaded By" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "album", label: "Album", type: "text", defaultValue: "General" },
    { key: "location", label: "Location", type: "text" },
    { key: "trade", label: "Trade", type: "text" },
    { key: "taken_date", label: "Date Taken", type: "date" },
    { key: "uploaded_by", label: "Uploaded By", type: "text" },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const timesheetsModule: ModuleConfig = {
  table: "timesheets",
  singular: "Timesheet",
  plural: "Timesheets",
  icon: "clock",
  searchField: "employee_name",
  projectScoped: true,
  columns: [
    { key: "employee_name", header: "Employee" },
    { key: "timesheet_date", header: "Date", type: "date" },
    { key: "hours_regular", header: "Regular" },
    { key: "hours_overtime", header: "OT" },
    { key: "cost_code", header: "Cost Code" },
    { key: "trade", header: "Trade" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "employee_name", label: "Employee Name", type: "text", required: true },
    { key: "timesheet_date", label: "Date", type: "date", required: true },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["pending", "submitted", "approved", "rejected"]), defaultValue: "pending" },
    { key: "hours_regular", label: "Regular Hours", type: "number" },
    { key: "hours_overtime", label: "OT Hours", type: "number" },
    { key: "hours_double", label: "Double Time", type: "number" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "trade", label: "Trade", type: "text" },
    { key: "billable", label: "Billable", type: "checkbox" },
    { key: "approved_by", label: "Approved By", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const inspectionsModule: ModuleConfig = {
  table: "inspections",
  singular: "Inspection",
  plural: "Inspections",
  icon: "clipboard-check",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "inspection_type", header: "Type", type: "badge" },
    { key: "inspector", header: "Inspector" },
    { key: "location", header: "Location" },
    { key: "inspection_date", header: "Date", type: "date" },
    { key: "result", header: "Result", type: "status" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Inspection #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "inspection_type", label: "Type", type: "select", options: STATUS_OPTS(["quality", "safety", "code", "pre-pour", "MEP"]), defaultValue: "quality" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["scheduled", "in_progress", "passed", "failed", "requires_action"]), defaultValue: "scheduled" },
    { key: "result", label: "Result", type: "select", options: STATUS_OPTS(["pass", "fail", "conditional"]) },
    { key: "inspector", label: "Inspector", type: "text" },
    { key: "trade", label: "Trade", type: "text" },
    { key: "location", label: "Location", type: "text" },
    { key: "inspection_date", label: "Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const observationsModule: ModuleConfig = {
  table: "observations",
  singular: "Observation",
  plural: "Observations",
  icon: "eye",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "observation_type", header: "Type", type: "badge" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "observed_date", header: "Observed", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Observation #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "observation_type", label: "Type", type: "select", options: STATUS_OPTS(["safety", "quality", "commissioning", "environmental"]), defaultValue: "safety" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["open", "in_progress", "resolved", "closed", "void"]), defaultValue: "open" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "location", label: "Location", type: "text" },
    { key: "trade", label: "Trade", type: "text" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "observed_by", label: "Observed By", type: "text" },
    { key: "observed_date", label: "Observed Date", type: "date" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "corrective_action", label: "Corrective Action", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const incidentsModule: ModuleConfig = {
  table: "incidents",
  singular: "Incident",
  plural: "Incidents",
  icon: "alert-circle",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "incident_type", header: "Type", type: "badge" },
    { key: "severity", header: "Severity", type: "badge" },
    { key: "incident_date", header: "Date", type: "date" },
    { key: "location", header: "Location" },
    { key: "osha_recordable", header: "OSHA" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Incident #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "incident_type", label: "Type", type: "select", options: STATUS_OPTS(["near_miss", "first_aid", "recordable", "lost_time", "property_damage", "environmental"]), defaultValue: "near_miss" },
    { key: "severity", label: "Severity", type: "select", options: STATUS_OPTS(["low", "medium", "high", "critical"]), defaultValue: "low" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["reported", "investigating", "corrective_action", "closed"]), defaultValue: "reported" },
    { key: "incident_date", label: "Date", type: "date" },
    { key: "incident_time", label: "Time", type: "text" },
    { key: "location", label: "Location", type: "text" },
    { key: "injured_party", label: "Injured Party", type: "text" },
    { key: "injury_type", label: "Injury Type", type: "text" },
    { key: "body_part", label: "Body Part", type: "text" },
    { key: "witness", label: "Witness", type: "text" },
    { key: "osha_recordable", label: "OSHA Recordable", type: "checkbox" },
    { key: "osha_case_number", label: "OSHA Case #", type: "text" },
    { key: "days_away", label: "Days Away", type: "number" },
    { key: "days_restricted", label: "Days Restricted", type: "number" },
    { key: "reported_by", label: "Reported By", type: "text" },
    { key: "investigated_by", label: "Investigated By", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "root_cause", label: "Root Cause", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const actionPlansModule: ModuleConfig = {
  table: "action_plans",
  singular: "Action Plan",
  plural: "Action Plans",
  icon: "target",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "title", header: "Title" },
    { key: "plan_type", header: "Type", type: "badge" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "due_date", header: "Due", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "plan_type", label: "Type", type: "select", options: STATUS_OPTS(["general", "safety", "quality", "environmental"]), defaultValue: "general" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "active", "completed", "cancelled"]), defaultValue: "draft" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "completed_date", label: "Completed Date", type: "date" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const correspondenceModule: ModuleConfig = {
  table: "correspondence",
  singular: "Correspondence",
  plural: "Correspondence",
  icon: "mail",
  searchField: "subject",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "subject", header: "Subject" },
    { key: "correspondence_type", header: "Type", type: "badge" },
    { key: "from_contact", header: "From" },
    { key: "to_contact", header: "To" },
    { key: "sent_date", header: "Sent", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Number", type: "text" },
    { key: "subject", label: "Subject", type: "text", required: true, span: 2 },
    { key: "correspondence_type", label: "Type", type: "select", options: STATUS_OPTS(["letter", "notice", "memo", "rfi_response", "transmittal"]), defaultValue: "letter" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "sent", "received", "replied"]), defaultValue: "draft" },
    { key: "from_company", label: "From Company", type: "text" },
    { key: "from_contact", label: "From Contact", type: "text" },
    { key: "to_company", label: "To Company", type: "text" },
    { key: "to_contact", label: "To Contact", type: "text" },
    { key: "cc", label: "CC", type: "text" },
    { key: "sent_date", label: "Sent Date", type: "date" },
    { key: "body", label: "Body", type: "textarea", span: 2 },
  ],
};

export const emailsModule: ModuleConfig = {
  table: "emails",
  singular: "Email",
  plural: "Emails",
  icon: "inbox",
  searchField: "subject",
  projectScoped: true,
  columns: [
    { key: "subject", header: "Subject" },
    { key: "from_address", header: "From" },
    { key: "status", header: "Status", type: "status" },
    { key: "sent_date", header: "Date", type: "date" },
  ],
  formFields: [
    { key: "subject", label: "Subject", type: "text", required: true, span: 2 },
    { key: "from_address", label: "From", type: "email" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "sent", "received"]), defaultValue: "draft" },
    { key: "sent_date", label: "Date", type: "date" },
    { key: "body", label: "Body", type: "textarea", span: 2 },
  ],
};

export const transmittalsModule: ModuleConfig = {
  table: "transmittals",
  singular: "Transmittal",
  plural: "Transmittals",
  icon: "send",
  searchField: "subject",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "subject", header: "Subject" },
    { key: "from_contact", header: "From" },
    { key: "to_contact", header: "To" },
    { key: "sent_via", header: "Via", type: "badge" },
    { key: "sent_date", header: "Sent", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Transmittal #", type: "text" },
    { key: "subject", label: "Subject", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "sent", "received", "acknowledged"]), defaultValue: "draft" },
    { key: "from_company", label: "From Company", type: "text" },
    { key: "from_contact", label: "From Contact", type: "text" },
    { key: "to_company", label: "To Company", type: "text" },
    { key: "to_contact", label: "To Contact", type: "text" },
    { key: "sent_via", label: "Sent Via", type: "select", options: STATUS_OPTS(["email", "mail", "hand_delivery", "courier"]), defaultValue: "email" },
    { key: "sent_date", label: "Sent Date", type: "date" },
    { key: "remarks", label: "Remarks", type: "textarea", span: 2 },
  ],
};

export const warrantiesModule: ModuleConfig = {
  table: "warranties",
  singular: "Warranty",
  plural: "Warranties",
  icon: "shield",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "title", header: "Title" },
    { key: "vendor", header: "Vendor" },
    { key: "warranty_type", header: "Type", type: "badge" },
    { key: "start_date", header: "Start", type: "date" },
    { key: "end_date", header: "End", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "warranty_type", label: "Type", type: "select", options: STATUS_OPTS(["standard", "extended", "manufacturer", "labor"]), defaultValue: "standard" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "expired", "claimed", "void"]), defaultValue: "active" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "duration_years", label: "Duration (years)", type: "number" },
    { key: "contact_name", label: "Contact Name", type: "text" },
    { key: "contact_phone", label: "Contact Phone", type: "text" },
    { key: "contact_email", label: "Contact Email", type: "email" },
    { key: "scope", label: "Scope", type: "textarea", span: 2 },
    { key: "terms", label: "Terms", type: "textarea", span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const projectDirectoryModule: ModuleConfig = {
  table: "project_directory",
  singular: "Contact",
  plural: "Project Directory",
  icon: "user-plus",
  searchField: "role",
  projectScoped: true,
  columns: [
    { key: "role", header: "Role" },
    { key: "notes", header: "Notes" },
    { key: "added_date", header: "Added", type: "date" },
  ],
  formFields: [
    { key: "role", label: "Role", type: "select", options: STATUS_OPTS(["project_manager", "superintendent", "foreman", "architect", "engineer", "owner_rep", "inspector", "subcontractor"]) },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

// ============================================================
// MISSING PROCORE MODULES — COMPANY LEVEL
// ============================================================

export const costCatalogModule: ModuleConfig = {
  table: "cost_catalog",
  singular: "Cost Code",
  plural: "Cost Catalog",
  icon: "dollar-sign",
  searchField: "description",
  columns: [
    { key: "code", header: "Code" },
    { key: "description", header: "Description" },
    { key: "category", header: "Category", type: "badge" },
    { key: "division", header: "Division" },
    { key: "unit", header: "Unit" },
    { key: "unit_cost", header: "Unit Cost", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "code", label: "Cost Code", type: "text", required: true },
    { key: "description", label: "Description", type: "text", required: true, span: 2 },
    { key: "category", label: "Category", type: "select", options: STATUS_OPTS(["labor", "material", "equipment", "subcontract", "other"]), defaultValue: "labor" },
    { key: "division", label: "Division", type: "text" },
    { key: "unit", label: "Unit", type: "text" },
    { key: "unit_cost", label: "Unit Cost", type: "currency" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "inactive"]), defaultValue: "active" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const companyDocumentsModule: ModuleConfig = {
  table: "company_documents",
  singular: "Document",
  plural: "Company Documents",
  icon: "folder",
  searchField: "name",
  columns: [
    { key: "name", header: "Name" },
    { key: "folder", header: "Folder" },
    { key: "document_type", header: "Type", type: "badge" },
    { key: "version", header: "Version" },
    { key: "uploaded_by", header: "Uploaded By" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true, span: 2 },
    { key: "folder", label: "Folder", type: "text", defaultValue: "/" },
    { key: "document_type", label: "Type", type: "select", options: STATUS_OPTS(["template", "policy", "procedure", "form", "general"]), defaultValue: "general" },
    { key: "version", label: "Version", type: "number", defaultValue: 1 },
    { key: "uploaded_by", label: "Uploaded By", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "archived"]), defaultValue: "active" },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const paymentsModule: ModuleConfig = {
  table: "payments",
  singular: "Payment",
  plural: "Payments",
  icon: "credit-card",
  searchField: "payee",
  columns: [
    { key: "payment_type", header: "Type", type: "badge" },
    { key: "payee", header: "Payee" },
    { key: "amount", header: "Amount", type: "currency" },
    { key: "payment_date", header: "Date", type: "date" },
    { key: "payment_method", header: "Method", type: "badge" },
    { key: "lien_waiver_status", header: "Lien Waiver", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "payment_type", label: "Type", type: "select", options: STATUS_OPTS(["outgoing", "incoming"]), defaultValue: "outgoing" },
    { key: "payee", label: "Payee", type: "text", required: true },
    { key: "payer", label: "Payer", type: "text" },
    { key: "amount", label: "Amount", type: "currency", required: true },
    { key: "payment_date", label: "Payment Date", type: "date" },
    { key: "payment_method", label: "Method", type: "select", options: STATUS_OPTS(["check", "ach", "wire", "credit_card"]), defaultValue: "check" },
    { key: "reference_number", label: "Reference #", type: "text" },
    { key: "invoice_number", label: "Invoice #", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["pending", "approved", "issued", "cleared", "void"]), defaultValue: "pending" },
    { key: "lien_waiver_status", label: "Lien Waiver", type: "select", options: STATUS_OPTS(["not_required", "pending", "conditional", "unconditional", "received"]), defaultValue: "not_required" },
    { key: "lien_waiver_type", label: "Waiver Type", type: "select", options: STATUS_OPTS(["conditional_progress", "unconditional_progress", "conditional_final", "unconditional_final"]) },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
  projectScoped: true,
};

export const workflowsModule: ModuleConfig = {
  table: "workflows",
  singular: "Workflow",
  plural: "Workflows",
  icon: "settings",
  searchField: "title",
  columns: [
    { key: "title", header: "Title" },
    { key: "workflow_type", header: "Type", type: "badge" },
    { key: "trigger_module", header: "Module", type: "badge" },
    { key: "trigger_event", header: "Event", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "workflow_type", label: "Type", type: "select", options: STATUS_OPTS(["approval", "review", "notification"]), defaultValue: "approval" },
    { key: "trigger_module", label: "Trigger Module", type: "select", options: STATUS_OPTS(["rfis", "submittals", "change_events", "owner_invoices", "commitments", "budget", "punch_list"]) },
    { key: "trigger_event", label: "Trigger Event", type: "select", options: STATUS_OPTS(["on_create", "on_status_change", "on_submit"]), defaultValue: "on_create" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "inactive", "draft"]), defaultValue: "draft" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

// ============================================================
// MISSING PROCORE MODULES — PROJECT LEVEL
// ============================================================

export const tasksModule: ModuleConfig = {
  table: "tasks",
  singular: "Task",
  plural: "Tasks",
  icon: "check-square",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "title", header: "Title" },
    { key: "category", header: "Category", type: "badge" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "due_date", header: "Due Date", type: "date" },
    { key: "percent_complete", header: "% Complete" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["open", "in_progress", "completed", "on_hold", "cancelled"]), defaultValue: "open" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "category", label: "Category", type: "select", options: STATUS_OPTS(["general", "safety", "quality", "design", "financial", "closeout"]) },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "completed_date", label: "Completed Date", type: "date" },
    { key: "percent_complete", label: "% Complete", type: "number" },
    { key: "related_module", label: "Related Module", type: "select", options: STATUS_OPTS(["rfi", "submittal", "punch_list", "inspection", "observation", "incident"]) },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const formsModule: ModuleConfig = {
  table: "forms",
  singular: "Form",
  plural: "Forms",
  icon: "clipboard-check",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "title", header: "Title" },
    { key: "form_type", header: "Type", type: "badge" },
    { key: "category", header: "Category", type: "badge" },
    { key: "created_by", header: "Created By" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "form_type", label: "Type", type: "select", options: STATUS_OPTS(["checklist", "inspection", "survey", "report", "custom"]), defaultValue: "checklist" },
    { key: "category", label: "Category", type: "select", options: STATUS_OPTS(["safety", "quality", "daily", "closeout", "general"]), defaultValue: "general" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "archived", "draft"]), defaultValue: "active" },
    { key: "created_by", label: "Created By", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const equipmentModule: ModuleConfig = {
  table: "equipment",
  singular: "Equipment",
  plural: "Equipment",
  icon: "settings",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Name" },
    { key: "equipment_type", header: "Type", type: "badge" },
    { key: "vendor", header: "Vendor" },
    { key: "ownership", header: "Ownership", type: "badge" },
    { key: "daily_rate", header: "Daily Rate", type: "currency" },
    { key: "location", header: "Location" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true, span: 2 },
    { key: "equipment_type", label: "Type", type: "select", options: STATUS_OPTS(["crane", "excavator", "loader", "forklift", "scaffold", "generator", "compressor", "other"]) },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "idle", "maintenance", "demobilized"]), defaultValue: "active" },
    { key: "make", label: "Make", type: "text" },
    { key: "model", label: "Model", type: "text" },
    { key: "serial_number", label: "Serial Number", type: "text" },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "ownership", label: "Ownership", type: "select", options: STATUS_OPTS(["owned", "rented", "leased"]), defaultValue: "rented" },
    { key: "daily_rate", label: "Daily Rate", type: "currency" },
    { key: "operator", label: "Operator", type: "text" },
    { key: "location", label: "Location", type: "text" },
    { key: "mobilization_date", label: "Mobilization Date", type: "date" },
    { key: "demobilization_date", label: "Demobilization Date", type: "date" },
    { key: "inspection_date", label: "Last Inspection", type: "date" },
    { key: "inspection_status", label: "Inspection Status", type: "select", options: STATUS_OPTS(["pass", "fail", "due"]) },
    { key: "hours_used", label: "Hours Used", type: "number" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const materialsModule: ModuleConfig = {
  table: "materials",
  singular: "Material",
  plural: "Materials",
  icon: "inbox",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Name" },
    { key: "category", header: "Category", type: "badge" },
    { key: "vendor", header: "Vendor" },
    { key: "quantity_ordered", header: "Ordered" },
    { key: "quantity_received", header: "Received" },
    { key: "total_cost", header: "Total Cost", type: "currency" },
    { key: "expected_delivery", header: "Expected", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true, span: 2 },
    { key: "category", label: "Category", type: "select", options: STATUS_OPTS(["concrete", "steel", "lumber", "electrical", "plumbing", "finishes", "other"]) },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["ordered", "in_transit", "received", "installed", "returned"]), defaultValue: "ordered" },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "quantity_ordered", label: "Qty Ordered", type: "number" },
    { key: "quantity_received", label: "Qty Received", type: "number" },
    { key: "quantity_installed", label: "Qty Installed", type: "number" },
    { key: "unit", label: "Unit", type: "text" },
    { key: "unit_cost", label: "Unit Cost", type: "currency" },
    { key: "total_cost", label: "Total Cost", type: "currency" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "po_number", label: "PO Number", type: "text" },
    { key: "tracking_number", label: "Tracking #", type: "text" },
    { key: "order_date", label: "Order Date", type: "date" },
    { key: "expected_delivery", label: "Expected Delivery", type: "date" },
    { key: "actual_delivery", label: "Actual Delivery", type: "date" },
    { key: "location", label: "Storage Location", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const crewsModule: ModuleConfig = {
  table: "crews",
  singular: "Crew",
  plural: "Crews",
  icon: "users",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Crew Name" },
    { key: "trade", header: "Trade" },
    { key: "foreman", header: "Foreman" },
    { key: "size", header: "Size" },
    { key: "shift", header: "Shift", type: "badge" },
    { key: "daily_rate", header: "Daily Rate", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Crew Name", type: "text", required: true },
    { key: "trade", label: "Trade", type: "text" },
    { key: "foreman", label: "Foreman", type: "text" },
    { key: "size", label: "Size", type: "number" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "inactive", "mobilizing"]), defaultValue: "active" },
    { key: "shift", label: "Shift", type: "select", options: STATUS_OPTS(["day", "night", "swing"]), defaultValue: "day" },
    { key: "daily_rate", label: "Daily Rate", type: "currency" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const fundingModule: ModuleConfig = {
  table: "funding",
  singular: "Funding Source",
  plural: "Funding",
  icon: "credit-card",
  searchField: "source_name",
  projectScoped: true,
  columns: [
    { key: "source_name", header: "Source" },
    { key: "funding_type", header: "Type", type: "badge" },
    { key: "total_amount", header: "Total", type: "currency" },
    { key: "drawn_amount", header: "Drawn", type: "currency" },
    { key: "remaining_amount", header: "Remaining", type: "currency" },
    { key: "expiry_date", header: "Expiry", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "source_name", label: "Source Name", type: "text", required: true, span: 2 },
    { key: "funding_type", label: "Type", type: "select", options: STATUS_OPTS(["owner", "bank", "bond", "grant", "insurance", "other"]), defaultValue: "owner" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "exhausted", "expired", "pending"]), defaultValue: "active" },
    { key: "total_amount", label: "Total Amount", type: "currency" },
    { key: "drawn_amount", label: "Drawn Amount", type: "currency" },
    { key: "remaining_amount", label: "Remaining", type: "currency" },
    { key: "contact_name", label: "Contact Name", type: "text" },
    { key: "contact_email", label: "Contact Email", type: "email" },
    { key: "contact_phone", label: "Contact Phone", type: "text" },
    { key: "account_number", label: "Account #", type: "text" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "expiry_date", label: "Expiry Date", type: "date" },
    { key: "terms", label: "Terms", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const tmTicketsModule: ModuleConfig = {
  table: "tm_tickets",
  singular: "T&M Ticket",
  plural: "T&M Tickets",
  icon: "receipt",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "vendor", header: "Vendor" },
    { key: "ticket_date", header: "Date", type: "date" },
    { key: "total_amount", header: "Total", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Ticket #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved", "rejected", "invoiced"]), defaultValue: "draft" },
    { key: "ticket_date", label: "Date", type: "date" },
    { key: "vendor", label: "Vendor", type: "text" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "submitted_by", label: "Submitted By", type: "text" },
    { key: "approved_by", label: "Approved By", type: "text" },
    { key: "labor_hours", label: "Labor Hours", type: "number" },
    { key: "labor_amount", label: "Labor Amount", type: "currency" },
    { key: "material_amount", label: "Material Amount", type: "currency" },
    { key: "equipment_amount", label: "Equipment Amount", type: "currency" },
    { key: "markup_percent", label: "Markup %", type: "number" },
    { key: "total_amount", label: "Total Amount", type: "currency" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

// ============================================================
// ADDITIONAL MISSING PROCORE MODULES — COMPANY LEVEL
// ============================================================

export const planroomModule: ModuleConfig = {
  table: "planroom",
  singular: "Plan Package",
  plural: "Planroom",
  icon: "folder",
  searchField: "title",
  columns: [
    { key: "title", header: "Package Title" },
    { key: "project_name", header: "Project" },
    { key: "bid_date", header: "Bid Date", type: "date" },
    { key: "trade", header: "Trade", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Package Title", type: "text", required: true, span: 2 },
    { key: "project_name", label: "Project Name", type: "text" },
    { key: "bid_date", label: "Bid Date", type: "date" },
    { key: "trade", label: "Trade / Scope", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "published", "closed", "awarded"]), defaultValue: "draft" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "documents_url", label: "Documents URL", type: "text", span: 2 },
    { key: "contact_name", label: "Contact Name", type: "text" },
    { key: "contact_email", label: "Contact Email", type: "email" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const resourcePlanningModule: ModuleConfig = {
  table: "resource_planning",
  singular: "Resource Assignment",
  plural: "Resource Planning",
  icon: "users",
  searchField: "resource_name",
  columns: [
    { key: "resource_name", header: "Resource" },
    { key: "resource_type", header: "Type", type: "badge" },
    { key: "project_name", header: "Project" },
    { key: "start_date", header: "Start", type: "date" },
    { key: "end_date", header: "End", type: "date" },
    { key: "allocation_pct", header: "Allocation %" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "resource_name", label: "Resource Name", type: "text", required: true, span: 2 },
    { key: "resource_type", label: "Type", type: "select", options: STATUS_OPTS(["labor", "equipment", "crew"]) },
    { key: "project_name", label: "Project", type: "text" },
    { key: "role", label: "Role / Function", type: "text" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "allocation_pct", label: "Allocation %", type: "number" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["planned", "confirmed", "active", "completed"]), defaultValue: "planned" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const companyScheduleModule: ModuleConfig = {
  table: "company_schedule",
  singular: "Schedule Item",
  plural: "Company Schedule",
  icon: "gantt-chart",
  searchField: "title",
  columns: [
    { key: "title", header: "Title" },
    { key: "project_name", header: "Project" },
    { key: "start_date", header: "Start", type: "date" },
    { key: "end_date", header: "End", type: "date" },
    { key: "milestone", header: "Milestone", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "project_name", label: "Project", type: "text" },
    { key: "start_date", label: "Start Date", type: "date" },
    { key: "end_date", label: "End Date", type: "date" },
    { key: "milestone", label: "Milestone", type: "select", options: STATUS_OPTS(["yes", "no"]), defaultValue: "no" },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["not_started", "in_progress", "completed", "delayed"]), defaultValue: "not_started" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const timecardsModule: ModuleConfig = {
  table: "timecards",
  singular: "Timecard",
  plural: "Timecards",
  icon: "clock",
  searchField: "employee_name",
  columns: [
    { key: "employee_name", header: "Employee" },
    { key: "date", header: "Date", type: "date" },
    { key: "project_name", header: "Project" },
    { key: "hours_regular", header: "Regular Hrs" },
    { key: "hours_overtime", header: "OT Hrs" },
    { key: "cost_code", header: "Cost Code" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "employee_name", label: "Employee Name", type: "text", required: true },
    { key: "date", label: "Date", type: "date", required: true },
    { key: "project_name", label: "Project", type: "text" },
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "hours_regular", label: "Regular Hours", type: "number" },
    { key: "hours_overtime", label: "Overtime Hours", type: "number" },
    { key: "hours_double", label: "Double Time Hours", type: "number" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved", "rejected"]), defaultValue: "draft" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const conversationsModule: ModuleConfig = {
  table: "conversations",
  singular: "Conversation",
  plural: "Conversations",
  icon: "mail",
  searchField: "subject",
  columns: [
    { key: "subject", header: "Subject" },
    { key: "channel", header: "Channel", type: "badge" },
    { key: "participants", header: "Participants" },
    { key: "last_message_at", header: "Last Activity", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "subject", label: "Subject", type: "text", required: true, span: 2 },
    { key: "channel", label: "Channel", type: "select", options: STATUS_OPTS(["general", "project", "safety", "financial"]) },
    { key: "participants", label: "Participants", type: "text", span: 2 },
    { key: "message", label: "Message", type: "textarea", span: 2 },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "archived"]), defaultValue: "active" },
  ],
};

export const permissionsModule: ModuleConfig = {
  table: "permission_templates",
  singular: "Permission Template",
  plural: "Permissions",
  icon: "shield-check",
  searchField: "name",
  columns: [
    { key: "name", header: "Template Name" },
    { key: "role", header: "Role", type: "badge" },
    { key: "tools_access", header: "Access Level", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Template Name", type: "text", required: true, span: 2 },
    { key: "role", label: "Role", type: "select", options: STATUS_OPTS(["admin", "project_manager", "superintendent", "foreman", "subcontractor", "read_only"]) },
    { key: "tools_access", label: "Access Level", type: "select", options: STATUS_OPTS(["full", "standard", "limited", "view_only"]) },
    { key: "can_create", label: "Can Create", type: "checkbox" },
    { key: "can_edit", label: "Can Edit", type: "checkbox" },
    { key: "can_delete", label: "Can Delete", type: "checkbox" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["active", "inactive"]), defaultValue: "active" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

// ============================================================
// ADDITIONAL MISSING PROCORE MODULES — PROJECT LEVEL
// ============================================================

export const instructionsModule: ModuleConfig = {
  table: "instructions",
  singular: "Instruction",
  plural: "Instructions",
  icon: "file-text",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "issued_to", header: "Issued To" },
    { key: "issued_date", header: "Issued", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Instruction #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "issued_by", label: "Issued By", type: "text" },
    { key: "issued_to", label: "Issued To", type: "text" },
    { key: "issued_date", label: "Issued Date", type: "date" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "issued", "acknowledged", "completed", "void"]), defaultValue: "draft" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const progressBillingsModule: ModuleConfig = {
  table: "progress_billings",
  singular: "Progress Billing",
  plural: "Progress Billings",
  icon: "receipt",
  searchField: "vendor_name",
  projectScoped: true,
  columns: [
    { key: "number", header: "Billing #" },
    { key: "vendor_name", header: "Vendor" },
    { key: "billing_period", header: "Period" },
    { key: "scheduled_value", header: "Scheduled Value", type: "currency" },
    { key: "work_completed", header: "Work Completed", type: "currency" },
    { key: "retainage", header: "Retainage", type: "currency" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Billing #", type: "text" },
    { key: "vendor_name", label: "Vendor Name", type: "text", required: true, span: 2 },
    { key: "billing_period", label: "Billing Period", type: "text" },
    { key: "billing_date", label: "Billing Date", type: "date" },
    { key: "scheduled_value", label: "Scheduled Value", type: "number" },
    { key: "previous_completed", label: "Previously Completed", type: "number" },
    { key: "work_completed", label: "This Period Completed", type: "number" },
    { key: "materials_stored", label: "Materials Stored", type: "number" },
    { key: "retainage", label: "Retainage", type: "number" },
    { key: "net_amount", label: "Net Amount Due", type: "number" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "submitted", "approved", "paid", "rejected"]), defaultValue: "draft" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const estimatingModule: ModuleConfig = {
  table: "estimates",
  singular: "Estimate Line",
  plural: "Estimating",
  icon: "dollar-sign",
  searchField: "description",
  projectScoped: true,
  columns: [
    { key: "cost_code", header: "Cost Code" },
    { key: "description", header: "Description" },
    { key: "category", header: "Category", type: "badge" },
    { key: "quantity", header: "Qty" },
    { key: "unit_cost", header: "Unit Cost", type: "currency" },
    { key: "total_cost", header: "Total", type: "currency" },
  ],
  formFields: [
    { key: "cost_code", label: "Cost Code", type: "text" },
    { key: "description", label: "Description", type: "text", required: true, span: 2 },
    { key: "category", label: "Category", type: "select", options: STATUS_OPTS(["labor", "material", "equipment", "subcontract", "overhead", "other"]) },
    { key: "quantity", label: "Quantity", type: "number" },
    { key: "unit", label: "Unit", type: "text" },
    { key: "unit_cost", label: "Unit Cost", type: "number" },
    { key: "total_cost", label: "Total Cost", type: "number" },
    { key: "markup_pct", label: "Markup %", type: "number" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const lienWaiversModule: ModuleConfig = {
  table: "lien_waivers",
  singular: "Lien Waiver",
  plural: "Lien Waivers",
  icon: "file-text",
  searchField: "vendor_name",
  projectScoped: true,
  columns: [
    { key: "vendor_name", header: "Vendor" },
    { key: "waiver_type", header: "Type", type: "badge" },
    { key: "amount", header: "Amount", type: "currency" },
    { key: "through_date", header: "Through Date", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "vendor_name", label: "Vendor Name", type: "text", required: true, span: 2 },
    { key: "waiver_type", label: "Waiver Type", type: "select", required: true, options: STATUS_OPTS(["conditional_progress", "unconditional_progress", "conditional_final", "unconditional_final"]) },
    { key: "amount", label: "Amount", type: "number" },
    { key: "through_date", label: "Through Date", type: "date" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["requested", "sent", "received", "approved"]), defaultValue: "requested" },
    { key: "signed_date", label: "Signed Date", type: "date" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const modelsModule: ModuleConfig = {
  table: "bim_models",
  singular: "Model",
  plural: "Models (BIM)",
  icon: "box",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Model Name" },
    { key: "discipline", header: "Discipline", type: "badge" },
    { key: "version", header: "Version" },
    { key: "file_format", header: "Format" },
    { key: "uploaded_date", header: "Uploaded", type: "date" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Model Name", type: "text", required: true, span: 2 },
    { key: "discipline", label: "Discipline", type: "select", options: STATUS_OPTS(["architectural", "structural", "mechanical", "electrical", "plumbing", "fire_protection", "civil", "coordination"]) },
    { key: "version", label: "Version", type: "text" },
    { key: "file_format", label: "File Format", type: "select", options: STATUS_OPTS(["ifc", "rvt", "nwc", "nwd", "dwg", "fbx"]) },
    { key: "file_url", label: "File URL", type: "text", span: 2 },
    { key: "uploaded_by", label: "Uploaded By", type: "text" },
    { key: "uploaded_date", label: "Upload Date", type: "date" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["current", "superseded", "archived"]), defaultValue: "current" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
  ],
};

export const coordinationIssuesModule: ModuleConfig = {
  table: "coordination_issues",
  singular: "Coordination Issue",
  plural: "Coordination Issues",
  icon: "alert-triangle",
  searchField: "title",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "title", header: "Title" },
    { key: "discipline", header: "Discipline", type: "badge" },
    { key: "assigned_to", header: "Assigned To" },
    { key: "due_date", header: "Due Date", type: "date" },
    { key: "priority", header: "Priority", type: "badge" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Issue #", type: "text" },
    { key: "title", label: "Title", type: "text", required: true, span: 2 },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "discipline", label: "Discipline", type: "select", options: STATUS_OPTS(["architectural", "structural", "mep", "electrical", "plumbing", "hvac", "fire_protection"]) },
    { key: "issue_type", label: "Issue Type", type: "select", options: STATUS_OPTS(["clash", "clearance", "routing", "design_conflict", "other"]) },
    { key: "assigned_to", label: "Assigned To", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "priority", label: "Priority", type: "select", options: PRIORITY_OPTS, defaultValue: "medium" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["open", "in_review", "resolved", "closed"]), defaultValue: "open" },
    { key: "location", label: "Location / Grid", type: "text" },
    { key: "resolution", label: "Resolution", type: "textarea", span: 2 },
  ],
};

export const projectBiddingModule: ModuleConfig = {
  table: "project_bidding",
  singular: "Bid Package",
  plural: "Bidding",
  icon: "gavel",
  searchField: "package_name",
  projectScoped: true,
  columns: [
    { key: "number", header: "#" },
    { key: "package_name", header: "Package" },
    { key: "trade", header: "Trade", type: "badge" },
    { key: "bid_due_date", header: "Bid Due", type: "date" },
    { key: "invitees_count", header: "Invitees" },
    { key: "bids_received", header: "Bids Received" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "number", label: "Package #", type: "text" },
    { key: "package_name", label: "Package Name", type: "text", required: true, span: 2 },
    { key: "trade", label: "Trade / Scope", type: "text" },
    { key: "description", label: "Description", type: "textarea", span: 2 },
    { key: "bid_due_date", label: "Bid Due Date", type: "date" },
    { key: "pre_bid_date", label: "Pre-Bid Date", type: "date" },
    { key: "estimated_value", label: "Estimated Value", type: "number" },
    { key: "invitees_count", label: "Invitees", type: "number" },
    { key: "bids_received", label: "Bids Received", type: "number" },
    { key: "awarded_to", label: "Awarded To", type: "text" },
    { key: "awarded_amount", label: "Awarded Amount", type: "number" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["draft", "published", "bidding", "evaluating", "awarded", "closed"]), defaultValue: "draft" },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

export const projectWorkflowsModule: ModuleConfig = {
  table: "project_workflows",
  singular: "Workflow",
  plural: "Workflows",
  icon: "settings",
  searchField: "name",
  projectScoped: true,
  columns: [
    { key: "name", header: "Workflow" },
    { key: "trigger_tool", header: "Tool", type: "badge" },
    { key: "current_step", header: "Current Step" },
    { key: "assigned_to", header: "Pending With" },
    { key: "status", header: "Status", type: "status" },
  ],
  formFields: [
    { key: "name", label: "Workflow Name", type: "text", required: true, span: 2 },
    { key: "trigger_tool", label: "Tool", type: "select", options: STATUS_OPTS(["rfis", "submittals", "change_orders", "invoices", "inspections", "punch_list"]) },
    { key: "trigger_record_id", label: "Record ID", type: "text" },
    { key: "current_step", label: "Current Step", type: "text" },
    { key: "assigned_to", label: "Pending With", type: "text" },
    { key: "status", label: "Status", type: "select", options: STATUS_OPTS(["pending", "in_progress", "approved", "rejected", "completed"]), defaultValue: "pending" },
    { key: "steps", label: "Steps (JSON)", type: "textarea", span: 2 },
    { key: "notes", label: "Notes", type: "textarea", span: 2 },
  ],
};

// All project-level modules in sidebar order
export const PROJECT_MODULES = [
  { key: "rfis", config: rfisModule, href: "rfis" },
  { key: "submittals", config: submittalsModule, href: "submittals" },
  { key: "drawings", config: drawingsModule, href: "drawings" },
  { key: "specifications", config: specificationsModule, href: "specifications" },
  { key: "schedule", config: scheduleModule, href: "schedule" },
  { key: "budget", config: budgetModule, href: "budget" },
  { key: "prime-contracts", config: primeContractsModule, href: "prime-contracts" },
  { key: "commitments", config: commitmentsModule, href: "commitments" },
  { key: "change-events", config: changeEventsModule, href: "change-events" },
  { key: "commitment-cos", config: commitmentCOsModule, href: "commitment-cos" },
  { key: "contract-cos", config: contractCOsModule, href: "contract-cos" },
  { key: "owner-invoices", config: ownerInvoicesModule, href: "owner-invoices" },
  { key: "sub-invoices", config: subInvoicesModule, href: "sub-invoices" },
  { key: "direct-costs", config: directCostsModule, href: "direct-costs" },
  { key: "daily-logs", config: dailyLogsModule, href: "daily-logs" },
  { key: "punch-list", config: punchListModule, href: "punch-list" },
  { key: "meetings", config: meetingsModule, href: "meetings" },
  { key: "documents", config: documentsModule, href: "documents" },
  { key: "photos", config: photosModule, href: "photos" },
  { key: "timesheets", config: timesheetsModule, href: "timesheets" },
  { key: "inspections", config: inspectionsModule, href: "inspections" },
  { key: "observations", config: observationsModule, href: "observations" },
  { key: "incidents", config: incidentsModule, href: "incidents" },
  { key: "action-plans", config: actionPlansModule, href: "action-plans" },
  { key: "correspondence", config: correspondenceModule, href: "correspondence" },
  { key: "emails", config: emailsModule, href: "emails" },
  { key: "transmittals", config: transmittalsModule, href: "transmittals" },
  { key: "warranties", config: warrantiesModule, href: "warranties" },
  { key: "directory", config: projectDirectoryModule, href: "directory" },
  { key: "tasks", config: tasksModule, href: "tasks" },
  { key: "forms", config: formsModule, href: "forms" },
  { key: "equipment", config: equipmentModule, href: "equipment" },
  { key: "materials", config: materialsModule, href: "materials" },
  { key: "crews", config: crewsModule, href: "crews" },
  { key: "funding", config: fundingModule, href: "funding" },
  { key: "tm-tickets", config: tmTicketsModule, href: "tm-tickets" },
  { key: "payments", config: paymentsModule, href: "payments" },
  { key: "instructions", config: instructionsModule, href: "instructions" },
  { key: "progress-billings", config: progressBillingsModule, href: "progress-billings" },
  { key: "estimating", config: estimatingModule, href: "estimating" },
  { key: "lien-waivers", config: lienWaiversModule, href: "lien-waivers" },
  { key: "models", config: modelsModule, href: "models" },
  { key: "coordination-issues", config: coordinationIssuesModule, href: "coordination-issues" },
  { key: "bidding", config: projectBiddingModule, href: "bidding" },
  { key: "workflows", config: projectWorkflowsModule, href: "workflows" },
] as const;
